# Generated by Django 6.0.2 on 2026-02-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
