# Generated by Django 6.0.2 on 2026-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(default=None, upload_to="resumes/"),
            preserve_default=False,
        ),
    ]
