# Generated by Django 6.0.2 on 2026-02-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_application_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interview_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
